name: 'Slacker'
description: 'Post a message to Slack'

inputs:
  webhook:
    description: 'Slack webhook'
    required: true

  message:
    description: 'Message to post'
    required: false
    default: 'Slacker says hi!'

runs:
  using: 'docker'
  image: 'Dockerfile'

  args:
    - ${{ inputs.webhook }}
    - ${{ inputs.message }}
