name: 'Slacker'
description: 'Post a message to Slack'

inputs:
  message:
    description: 'Message to post'
    required: false
    default: 'Slacker says hi!'

runs:
  using: 'docker'
  image: 'Dockerfile'

  env:
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  args:
    - ${{ inputs.message }}
