name: 'Slacker'
description: 'Post a message to Slack'

inputs:
  status:
    description: 'Message to send'
    required: true
    default: 'Slacker says hi!'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.status }}
